import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { loadEnv, type Plugin } from 'vite';

type FirebaseEnvConfig = {
  apiKey: string;
  authDomain: string;
  projectId: string;
  storageBucket: string;
  messagingSenderId: string;
  appId: string;
};

function readFirebaseEnv(mode: string): FirebaseEnvConfig {
  const env = loadEnv(mode, process.cwd(), '');
  return {
    apiKey: env.VITE_FIREBASE_API_KEY ?? '',
    authDomain: env.VITE_FIREBASE_AUTH_DOMAIN ?? '',
    projectId: env.VITE_FIREBASE_PROJECT_ID ?? '',
    storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET ?? '',
    messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID ?? '',
    appId: env.VITE_FIREBASE_APP_ID ?? '',
  };
}

function writeFirebaseConfig(mode: string): void {
  const config = readFirebaseEnv(mode);
  const outputPath = resolve(process.cwd(), 'public/firebase-config.js');
  const content = `// Auto-generated by Vite — do not edit manually.\nself.FIREBASE_CONFIG = ${JSON.stringify(config)};\n`;
  writeFileSync(outputPath, content, 'utf8');
}

export function firebaseConfigPlugin(): Plugin {
  let resolvedMode = 'development';

  return {
    name: 'firebase-config',
    configResolved(config) {
      resolvedMode = config.mode;
      writeFirebaseConfig(resolvedMode);
    },
    buildStart() {
      writeFirebaseConfig(resolvedMode);
    },
  };
}
